version: '3.3'

services:
  db:
    image: postgres:14  # Utiliza una versión específica
    container_name: postgres_db
    environment:
      POSTGRES_DB: festiva-db     # Nombre de la base de datos a crear
      POSTGRES_USER: festiva        # Usuario de la base de datos
      POSTGRES_PASSWORD: festiva-89320 # Contraseña del usuario
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistencia de datos
    ports:
      - "5432:5432"  # Mapea el puerto 5432
    restart: unless-stopped  # Reinicia el contenedor a menos que se detenga manualmente
  redis:
    image: redis:7.4
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - redis_network
  redisinsight:
    image: redislabs/redisinsight:2.66
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - redis_network
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data
volumes:
  db_data:  # Define el volumen para la persistencia
  redis_data:
    driver: local
  redisinsight_data:
    driver: local
networks:
  redis_network:
    driver: bridge
