### Obtener todos los productos
GET http://localhost:8088/v1.0/products
Content-Type: application/json

### Obtener productos con parámetros de búsqueda
GET http://localhost:8088/v1.0/products?name=licor&page=0&size=10
Content-Type: application/json

### Obtener un producto por ID
GET http://localhost:8088/v1.0/products/DZPe5VHZ1bsq4Lr-FySURw
Content-Type: application/json

### Crear un nuevo producto
POST http://localhost:8088/v1.0/products
Content-Type: application/json

{
  "name": "Producto 4",
  "description": "Descripción del producto 4",
  "amount": 49.99,
  "stock": 4,
  "expirationDate": "2025-12-03",
  "size": "M",
  "idTypeProduct": 1,
  "idProvider": 1
}

### Actualizar un producto existente
PUT http://localhost:8088/v1.0/products/a3FrJTk8-Gl1B7-WmLTC3Q
Content-Type: application/json

{
  "name": "Producto Actualizado",
  "description": "Nueva descripción del producto",
  "amount": 39.99,
  "stock": 150,
  "expirationDate": "2026-12-31",
  "size": "L",
  "idTypeProduct": 1,
  "idProvider": 1
}

### Eliminar un producto
DELETE http://localhost:8088/v1.0/products/a3FrJTk8-Gl1B7-WmLTC3Q
Content-Type: application/json